// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyRrBkAlqE6wOXOEL7AyUQbBm6P0LY9ZQ',
    appId: '1:406693059088:web:13950cb836e19406dd0895',
    messagingSenderId: '406693059088',
    projectId: 'semester-app-project-79c03',
    authDomain: 'semester-app-project-79c03.firebaseapp.com',
    storageBucket: 'semester-app-project-79c03.firebasestorage.app',
    measurementId: 'G-P1JQN2D857',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbHYaXzGTlJTbeCuZYQChoMmt6xO9uw2s',
    appId: '1:406693059088:android:fa9d8bcf3ac16d8edd0895',
    messagingSenderId: '406693059088',
    projectId: 'semester-app-project-79c03',
    storageBucket: 'semester-app-project-79c03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkEbzSrGq_SnKFwPe0LCtpRPnRfOuA2-0',
    appId: '1:406693059088:ios:d2d3b46cce5a9117dd0895',
    messagingSenderId: '406693059088',
    projectId: 'semester-app-project-79c03',
    storageBucket: 'semester-app-project-79c03.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkEbzSrGq_SnKFwPe0LCtpRPnRfOuA2-0',
    appId: '1:406693059088:ios:d2d3b46cce5a9117dd0895',
    messagingSenderId: '406693059088',
    projectId: 'semester-app-project-79c03',
    storageBucket: 'semester-app-project-79c03.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyRrBkAlqE6wOXOEL7AyUQbBm6P0LY9ZQ',
    appId: '1:406693059088:web:f3da83cc6bf51861dd0895',
    messagingSenderId: '406693059088',
    projectId: 'semester-app-project-79c03',
    authDomain: 'semester-app-project-79c03.firebaseapp.com',
    storageBucket: 'semester-app-project-79c03.firebasestorage.app',
    measurementId: 'G-X63D9DQV0F',
  );
}
